apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manthanai-ingress
  namespace: manthanai
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - manthanai.example.com
      secretName: manthanai-tls
  rules:
    - host: manthanai.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: manthanai-backend-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: manthanai-frontend-service
                port:
                  number: 3000
